package com.araujo.jordan.wordfindify

import android.os.Bundle
import android.widget.TextView
import androidx.appcompat.app.AppCompatActivity
import kotlinx.android.synthetic.main.board_activity.*
import java.util.*

class BoardActivity : AppCompatActivity(), BoardListener {

    private var boardController: CharacterController? = null

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.board_activity)

        boardController = CharacterController(this)
        boardController?.board = buildBoard()
        boardController?.reset()
    }

    private fun buildBoard(): ArrayList<ArrayList<TextView>> {
        val board = ArrayList<ArrayList<TextView>>()
        val line = ArrayList<TextView>()
        line.add(board00)
        line.add(board10)
        line.add(board20)
        line.add(board30)
        line.add(board40)
        line.add(board50)
        line.add(board60)
        line.add(board70)
        line.add(board80)
        line.add(board90)
        board.add(line)
        val line1 = ArrayList<TextView>()
        line1.add(board01)
        line1.add(board11)
        line1.add(board21)
        line1.add(board31)
        line1.add(board41)
        line1.add(board51)
        line1.add(board61)
        line1.add(board71)
        line1.add(board81)
        line1.add(board91)
        board.add(line1)
        val line2 = ArrayList<TextView>()
        line2.add(board02)
        line2.add(board12)
        line2.add(board22)
        line2.add(board32)
        line2.add(board42)
        line2.add(board52)
        line2.add(board62)
        line2.add(board72)
        line2.add(board82)
        line2.add(board92)
        board.add(line2)
        val line3 = ArrayList<TextView>()
        line3.add(board03)
        line3.add(board13)
        line3.add(board23)
        line3.add(board33)
        line3.add(board43)
        line3.add(board53)
        line3.add(board63)
        line3.add(board73)
        line3.add(board83)
        line3.add(board93)
        board.add(line3)
        val line4 = ArrayList<TextView>()
        line4.add(board04)
        line4.add(board14)
        line4.add(board24)
        line4.add(board34)
        line4.add(board44)
        line4.add(board54)
        line4.add(board64)
        line4.add(board74)
        line4.add(board84)
        line4.add(board94)
        board.add(line4)
        val line5 = ArrayList<TextView>()
        line5.add(board05)
        line5.add(board15)
        line5.add(board25)
        line5.add(board35)
        line5.add(board45)
        line5.add(board55)
        line5.add(board65)
        line5.add(board75)
        line5.add(board85)
        line5.add(board95)
        board.add(line5)
        val line6 = ArrayList<TextView>()
        line6.add(board06)
        line6.add(board16)
        line6.add(board26)
        line6.add(board36)
        line6.add(board46)
        line6.add(board56)
        line6.add(board66)
        line6.add(board76)
        line6.add(board86)
        line6.add(board96)
        board.add(line6)
        val line7 = ArrayList<TextView>()
        line7.add(board07)
        line7.add(board17)
        line7.add(board27)
        line7.add(board37)
        line7.add(board47)
        line7.add(board57)
        line7.add(board67)
        line7.add(board77)
        line7.add(board87)
        line7.add(board97)
        board.add(line7)
        val line8 = ArrayList<TextView>()
        line8.add(board08)
        line8.add(board18)
        line8.add(board28)
        line8.add(board38)
        line8.add(board48)
        line8.add(board58)
        line8.add(board68)
        line8.add(board78)
        line8.add(board88)
        line8.add(board98)
        board.add(line8)
        val line9 = ArrayList<TextView>()
        line9.add(board09)
        line9.add(board19)
        line9.add(board29)
        line9.add(board39)
        line9.add(board49)
        line9.add(board59)
        line9.add(board69)
        line9.add(board79)
        line9.add(board89)
        line9.add(board99)
        board.add(line9)
        return board
    }

    override fun onVictory() {

    }

    override fun removeWord(charactersBetween: ArrayList<TextView>) {

    }
}
